name: Development workflow

on: push

jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use cache
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: modules-${{github.sha}}
      - name: Use node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install

  Build:
    runs-on: ubuntu-latest
    needs: Install
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use cache
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: modules-${{github.sha}}
      - name: Use node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Build react app
        run: npm run build